name: Deploy MERN Stack App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Specify your Node.js version

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Deploy Backend to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: your-backend-app-name
      run: |
        npm install -g heroku
        heroku git:remote -a $HEROKU_APP_NAME
        git subtree push --prefix backend heroku main

    - name: Deploy Frontend to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        npm install -g netlify-cli
        netlify deploy --dir=frontend/build --prod
